"""empty message

Revision ID: 3e6be4a4d6cf
Revises: 
Create Date: 2024-11-06 19:16:32.716183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6be4a4d6cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swiss_match', schema=None) as batch_op:
        batch_op.alter_column('participant2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swiss_match', schema=None) as batch_op:
        batch_op.alter_column('participant2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
